# Generated by Django 4.2.27 on 2026-01-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='destination',
            field=models.CharField(help_text='Destination in which blog post is related to', max_length=200),
        ),
    ]
