# Generated by Django 4.2.27 on 2026-05-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_destination'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Slug',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='destination',
            field=models.CharField(help_text='Destination which the blog post is related to', max_length=200),
        ),
    ]
